import * as fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { safePath, rootOf, readText, readJSON, atomicWrite, sha256, canonical } from './fs.mjs';
import { validatePolicy, validatePlan } from './schema.mjs';
import { insist } from './errors.mjs';
export const PACKAGE_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
function installSkills(root, host, write = atomicWrite) {
    const created = [], skipped = [];
    const destination = host === 'claude' ? '.claude/skills' : '.agents/skills';
    const source = path.join(PACKAGE_ROOT, 'skills');
    function copy(directory, relative = '') {
        for (const item of fs.readdirSync(directory, { withFileTypes: true })) {
            insist(!item.isSymbolicLink(), 'BAD_SKILL_SOURCE', 'Skill sources must be regular files or directories.');
            const suffix = path.posix.join(relative, item.name);
            const absolute = path.join(directory, item.name);
            if (item.isDirectory()) {
                if (host !== 'claude' || item.name !== 'agents') copy(absolute, suffix);
                continue;
            }
            insist(item.isFile(), 'BAD_SKILL_SOURCE', 'Unsupported skill source entry.');
            const rel = `${destination}/${suffix}`;
            if (fs.existsSync(safePath(root, rel))) { skipped.push(rel); continue; }
            let body = readText(absolute);
            if (host === 'claude' && /steward-(policy|schedule)\/SKILL\.md$/.test(suffix))
                body = body.replace(/^---\r?\n/, '---\ndisable-model-invocation: true\n');
            write(root, rel, body);
            created.push(rel);
        }
    }
    copy(source);
    return { created, skipped };
}
function writeUsage(root, write = atomicWrite) {
    const rel = '.steward/USAGE.md';
    const prefix = [process.execPath, path.join(PACKAGE_ROOT, 'bin/steward.mjs'), '--project', root].map(quote).join(' ');
    const body = '# Steward local runner\n\nGenerated by init/install. Do not edit; rerun after moving the toolkit.\n' +
        '\nUse this exact command prefix, then append a command such as `journal list`, `verify` or `gate`:\n\n' +
        '```' + (process.platform === 'win32' ? 'bat' : 'sh') + '\n' + prefix + '\n```\n\n' +
        'This is ' + (process.platform === 'win32' ? 'cmd.exe' : 'POSIX shell') + ' syntax. For another execution tool, pass the executable and arguments separately; do not blindly re-quote it.\n\n' +
        'Executable: ' + JSON.stringify(process.execPath) + '\n\nCLI script: ' + JSON.stringify(path.join(PACKAGE_ROOT, 'bin/steward.mjs')) +
        '\n\nProject: ' + JSON.stringify(root) + '\n\nExample JSON directory: ' + JSON.stringify(path.join(PACKAGE_ROOT, 'examples')) + '\n\n' +
        'Use actual user data rather than fixture text. The initial verification plan deliberately fails until configured.\n';
    write(root, rel, body, { replace: fs.existsSync(safePath(root, rel)) });
}
export function initProject(project) {
    fs.mkdirSync(path.resolve(project), { recursive: true });
    const root = rootOf(project);
    const policy = validatePolicy(readJSON(path.join(PACKAGE_ROOT, 'profiles/default-policy.json')));
    const plan = validatePlan(readJSON(path.join(PACKAGE_ROOT, 'profiles/default-verify.json')));
    const files = [['.steward/policy.json', JSON.stringify(policy, null, 2) + '\n'], ['.steward/verify.json', JSON.stringify(plan, null, 2) + '\n'], ['.steward/agent-profile.json', readText(path.join(PACKAGE_ROOT, 'profiles/agent-workflow.json'))]];
    const created = [], skipped = [];
    for (const [rel, body] of files) {
        if (fs.existsSync(safePath(root, rel))) { skipped.push(rel); continue; }
        atomicWrite(root, rel, body);
        created.push(rel);
    }
    const skills = installSkills(root, 'codex');
    created.push(...skills.created); skipped.push(...skills.skipped);
    writeUsage(root);
    const block = readText(path.join(PACKAGE_ROOT, 'profiles/AGENTS-snippet.md'));
    const ap = safePath(root, 'AGENTS.md');
    const old = fs.existsSync(ap) ? readText(ap) : '';
    if (!old.includes('<!-- steward:start -->')) {
        atomicWrite(root, 'AGENTS.md', old + (old ? '\n\n' : '') + block, { replace: fs.existsSync(ap) });
        created.push('AGENTS.md');
    } else skipped.push('AGENTS.md');
    const gp = safePath(root, '.gitignore');
    const gi = fs.existsSync(gp) ? readText(gp) : '';
    const additions = ['.steward/state/', '.steward/USAGE.md', '.steward/install-*.json', '.codex/hooks.json', '.claude/settings.local.json'].filter(x => !gi.split('\n').includes(x));
    if (additions.length)
        atomicWrite(root, '.gitignore', gi + (gi && !gi.endsWith('\n') ? '\n' : '') + additions.join('\n') + '\n', { replace: fs.existsSync(gp) });
    return { project: root, profile: 'default', created, skipped, generated: ['.steward/USAGE.md'], trusted: false, note: 'The verification plan deliberately fails until you configure real project checks. Existing files are preserved; review skipped skill files when upgrading.' };
}
function quote(arg) {
    if (process.platform === 'win32') {
        insist(!/["%!\r\n<>|&]/.test(arg), 'UNSAFE_INSTALL_PATH', 'Windows installation path contains unsupported command-shell characters.');
        return '"' + arg + '"';
    }
    return "'" + arg.replaceAll("'", "'\\''") + "'";
}
// Preflight every target before activation, then restore completed writes on failure.
// Like atomicWrite, this coordinates local use, not hostile concurrent filesystem edits.
function applyInstallation(root, writes) {
    const completed = [];
    try {
        for (const item of writes) {
            atomicWrite(root, item.relative, item.body, { replace: item.before !== null });
            completed.push(item);
            if (item.before !== null) fs.chmodSync(safePath(root, item.relative), item.mode);
        }
    }
    catch {
        const failed = [];
        for (const item of completed.reverse()) {
            try {
                if (item.before === null) fs.unlinkSync(safePath(root, item.relative));
                else {
                    atomicWrite(root, item.relative, item.before, { replace: true });
                    fs.chmodSync(safePath(root, item.relative), item.mode);
                }
            }
            catch { failed.push(item.relative); }
        }
        insist(!failed.length, 'INSTALL_RECOVERY_REQUIRED', `Installation failed; could not restore: ${failed.join(', ')}. Inspect these files before using hooks.`);
        insist(false, 'INSTALL_FAILED', 'Installation failed; completed file writes were restored. Empty created directories may remain.');
    }
}
export function installHooks(root, host) {
    const lock = safePath(root, '.steward/install.lock');
    try { fs.mkdirSync(lock, { mode: 0o700 }); }
    catch (error) {
        if (error.code === 'EEXIST') insist(false, 'INSTALL_LOCKED', 'Another installer holds the lock. Recover a crashed installer before retrying.');
        throw error;
    }
    try { return prepareInstallation(root, host); }
    finally { fs.rmdirSync(lock); }
}
function prepareInstallation(root, host) {
    insist(['codex', 'claude'].includes(host), 'BAD_HOST', 'Install supports codex or claude.');
    const writes = [];
    const stage = (_, relative, body) => {
        const target = safePath(root, relative);
        const exists = fs.existsSync(target);
        const before = exists ? readText(target) : null;
        // Existing ancestors must be directories, including for currently absent targets.
        let directory = path.dirname(target);
        while (directory !== root) {
            if (fs.existsSync(directory)) insist(fs.statSync(directory).isDirectory(), 'INSTALL_CONFLICT', `Not a directory: ${path.relative(root, directory)}`);
            directory = path.dirname(directory);
        }
        writes.push({ relative, body, before, mode: exists ? fs.statSync(target).mode & 0o777 : null });
    };
    const rel = host === 'codex' ? '.codex/hooks.json' : '.claude/settings.local.json';
    const target = safePath(root, rel);
    const config = fs.existsSync(target) ? readJSON(target) : {};
    insist(config && typeof config === 'object' && !Array.isArray(config), 'INSTALL_CONFLICT', 'Existing host configuration is not an object.');
    config.hooks ??= {};
    insist(config.hooks && typeof config.hooks === 'object' && !Array.isArray(config.hooks), 'INSTALL_CONFLICT', 'Existing hooks field is not an object.');
    const receiptPath = `.steward/install-${host}.json`, rp = safePath(root, receiptPath);
    const old = fs.existsSync(rp) ? readJSON(rp) : { commands: [] };
    insist(old && Array.isArray(old.commands) && old.commands.every(c => typeof c === 'string'), 'INSTALL_CONFLICT', 'Invalid previous installation receipt.');
    const commands = [];
    for (const event of ['SessionStart', 'UserPromptSubmit', 'PreToolUse', 'PreCompact']) {
        const command = [process.execPath, path.join(PACKAGE_ROOT, 'bin/steward.mjs'), 'hook', '--host', host, '--project', root, '--event', event].map(quote).join(' ');
        const arr = config.hooks[event] ?? [];
        insist(Array.isArray(arr), 'INSTALL_CONFLICT', `Existing ${event} config is not an array.`);
        // Remove only an exact command recorded by our previous installer; preserve other handlers.
        const preserved = [];
        for (const entry of arr) {
            insist(entry && Array.isArray(entry.hooks), 'INSTALL_CONFLICT', 'Existing hook entry has an unsupported shape.');
            const hooks = entry.hooks.filter(h => !old.commands.includes(h.command) && h.command !== command);
            if (hooks.length)
                preserved.push({ ...entry, hooks });
        }
        config.hooks[event] = [...preserved, { ...(event === 'PreToolUse' ? { matcher: '.*' } : {}), hooks: [{ type: 'command', command, timeout: 10 }] }];
        commands.push(command);
    }
    stage(root, rel, JSON.stringify(config, null, 2) + '\n');
    stage(root, receiptPath, JSON.stringify({ version: 1, host, commands, configHash: sha256(canonical(config)) }, null, 2) + '\n');
    const skills = installSkills(root, host, stage);
    writeUsage(root, stage);
    if (host === 'claude') {
        const cp = safePath(root, 'CLAUDE.md'), text = fs.existsSync(cp) ? readText(cp) : '';
        const oldPointer = '<!-- steward:claude -->\nRead AGENTS.md for the project working agreement and .agents/skills/steward-* for relevant procedures.\n';
        const block = '<!-- steward:claude -->\n@AGENTS.md\n<!-- steward:claude:end -->\n';
        let next = text.replace(oldPointer, block);
        if (!/(^|\n)@AGENTS\.md[ \t]*(\r?\n|$)/.test(next))
            next += (next && !next.endsWith('\n') ? '\n' : '') + '\n' + block;
        if (next !== text)
            stage(root, 'CLAUDE.md', next);
    }
    applyInstallation(root, writes);
    return { host, path: rel, installed: true, skills, hostTrustRequired: true, liveHostVerified: false };
}
